#!/bin/sh

rm -rf output.generated/

mkdir -p tmp.generated/

cat externals/jquery-ui/dist/jquery-ui.css template/shufflestega.css > tmp.generated/stegashuffle.css

python build.py externals/closure-compiler/build/compiler.jar output.generated/CONFIGURATION/shufflestega.html template/shufflestega.html template/pagelet/ tmp.generated/stegashuffle.css

rm -rf tmp.generated/
